jobs:
  run:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./check/action

name: Run

on:
  schedule:
    - cron: "15 0/3 * * *"
